FROM texlive/texlive:TL2022-historic
COPY --from=texlive/texlive:TL2023-historic /usr/local/texlive/2023/texmf-dist/tex/latex/csbulletin/* /usr/local/texlive/2022/texmf-dist/tex/latex/csbulletin/
RUN luaotfload-tool -u || true
RUN cp "$(find /usr/local/texlive -name texlive-fontconfig.conf)" /etc/fonts/conf.d/09-texlive-fonts.conf || true
RUN fc-cache -fsv
# From `StaryNovotny-fantasia/.github/workflows/main.yml`:
RUN apt-get -qy update
RUN apt-get -qy install --no-install-recommends ffmpeg make imagemagick jpegoptim optipng pdftk
