.PHONY: all do-once-at-the-start preview clear FORCE

DOCKER = docker run --rm -u $(shell id -u):$(shell id -g) --env TEXMFVAR=/var/tmp/texmf-var -v "$$PWD"/..:/workdir -w /workdir/"$$(basename "$$PWD")"
IMAGE = texlive/texlive:TL2022-historic-with-cache-fantasia
LATEXMK = latexmk -lualatex -shell-escape -f
DOCUMENT = main.tex

all: $(basename $(DOCUMENT)).pdf

do-once-at-the-start: FORCE
	cp ../fantasia-effects-406.png images/screen2-czech/
	mogrify -resize 2100x1500\> -quality 100% images/audacity.png images/flowblade.png images/screen3.png images/montage.jpg
	optipng -o 7 images/audacity.png images/flowblade.png images/screen3.png
	jpegoptim -m85 images/montage.jpg

preview: $(DOCUMENT)
	$(DOCKER) $(IMAGE) $(LATEXMK) -pvc $<

clear: $(DOCUMENT)
	$(DOCKER) $(IMAGE) $(LATEXMK) -C $<

%.pdf: %.tex FORCE
	rm -f $(basename $@).bbl $(basename $@).pax
	$(DOCKER) $(IMAGE) $(MAKE) -C images/
	$(DOCKER) $(IMAGE) $(MAKE) -C images/frames/
	$(DOCKER) $(IMAGE) $(MAKE) -C images/screen2-czech/ fantasia.pdf fantasia-background.pdf fantasia-text.pdf
	$(DOCKER) $(IMAGE) $(MAKE) -C images/transition/
	$(DOCKER) $(IMAGE) $(LATEXMK) $<
	# Convert image `camcorder-minterpolate-yadif.pdf` to grayscale for printing.
	grep -F '\csbul@webtrue' $(basename $@).info || (cp -v images/camcorder-minterpolate-yadif.pdf images/camcorder-minterpolate-yadif.pdf.bak && ../pdf-to-grayscale.sh images/camcorder-minterpolate-yadif.pdf)
	$(DOCKER) $(IMAGE) $(LATEXMK) $<
	# Restore the original image `camcorder-minterpolate-yadif.pdf`.
	grep -F '\csbul@webtrue' $(basename $@).info || (mv -v images/camcorder-minterpolate-yadif.pdf.bak images/camcorder-minterpolate-yadif.pdf)
	touch $(basename $@).info
	! grep -F '\csbul@webtrue' $(basename $@).info || $(DOCKER) $(IMAGE) pdfannotextractor $@
