name: latexmk
on: [push]
jobs:
  action-test:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest
    permissions:
      contents: write
    steps:
      - name: Stáhni repozitář
        uses: actions/checkout@v4
      - name: Zkompiluj LaTeXové dokumenty
        run: "latexmk --lualatex"
      - name: Přesuň soubory PDF do adresáře build
        run: mkdir -p build && mv *.pdf build/
      - name: Publikuj soubory PDF do gitové větve pdf-output
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: build
          target_branch: pdf-output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Ulož dokumentaci
        uses: actions/upload-artifact@v4
        with:
          name: Documentation
          path: "./*.pdf"
          retention-days: 3
