name: Typeset CSTUG Bulletin
on:
- push
permissions:
  contents: write
env:
  DEBIAN_FRONTEND: noninteractive
jobs:
  build:
    name: Typeset CSTUG Bulletin
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install requirements
        run: |
          set -e
          sudo apt update
          sudo apt install -y ghostscript libxml2-utils moreutils optipng parallel poppler-utils python3-pdfminer jpegoptim imagemagick
#     - name: Validate metadata
#       run: make test-xml
      - name: Build Docker images
        run: make images
      - name: Typeset CSTUG Bulletin
        run: make all
      - name: Upload PDF documents as build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: |
            bul.pdf
            bul-web.pdf
            bul-obalka-margins-*mm.pdf
            bul-blok-margins-*mm.pdf
      - name: Validate PDF documents
        run: make test
      - name: Upload PDF documents as a release
        if: github.ref == 'refs/heads/main'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: The latest version
          automatic_release_tag: latest
          prerelease: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            bul.pdf
            bul-web.pdf
            bul-obalka-margins-*mm.pdf
            bul-blok-margins-*mm.pdf
